// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCAxgJBHybTpeskbtt2JmoPlIvK9YO7ds',
    appId: '1:790604076675:web:a8e8bf26bd98cb45616db6',
    messagingSenderId: '790604076675',
    projectId: 'flutter-lesson-91eec',
    authDomain: 'flutter-lesson-91eec.firebaseapp.com',
    databaseURL: 'https://flutter-lesson-91eec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lesson-91eec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5-QfhIwFEzT217CFSR0zgY5PSpuhh6PU',
    appId: '1:790604076675:android:1e8d58309f3f9035616db6',
    messagingSenderId: '790604076675',
    projectId: 'flutter-lesson-91eec',
    databaseURL: 'https://flutter-lesson-91eec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lesson-91eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB39HwYKRL5T1A9a0P6RAUIaREZp7yGrY',
    appId: '1:790604076675:ios:55bbf2b2c179147b616db6',
    messagingSenderId: '790604076675',
    projectId: 'flutter-lesson-91eec',
    databaseURL: 'https://flutter-lesson-91eec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lesson-91eec.firebasestorage.app',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB39HwYKRL5T1A9a0P6RAUIaREZp7yGrY',
    appId: '1:790604076675:ios:55bbf2b2c179147b616db6',
    messagingSenderId: '790604076675',
    projectId: 'flutter-lesson-91eec',
    databaseURL: 'https://flutter-lesson-91eec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lesson-91eec.firebasestorage.app',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCAxgJBHybTpeskbtt2JmoPlIvK9YO7ds',
    appId: '1:790604076675:web:a2e95fd64c940b8d616db6',
    messagingSenderId: '790604076675',
    projectId: 'flutter-lesson-91eec',
    authDomain: 'flutter-lesson-91eec.firebaseapp.com',
    databaseURL: 'https://flutter-lesson-91eec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lesson-91eec.firebasestorage.app',
  );
}
